[package]
name = "itau-desafio-programacao"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
chrono = "0.4.41"
dotenvy = "0.15.7"
env_logger = "0.11.8"
log = "0.4.27"
serde = "1.0.219"
thiserror = "2.0.16"
uuid = { version = "1.18.0", features = ["v4"] }
